version: "3.5"

services:
    postgres:
        image: postgres:12
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
        volumes:
            - postgres-volume:/var/lib/postgresql/data
    redis:
        image: "redis:alpine"
        ports:
            - 6379:6379

volumes:
    postgres-volume: